[target.thumbv6m-none-eabi]
runner = "probe-rs run --chip RP2040"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
rustflags = ["-C", "link-arg=-Tlink.x", "-C", "link-arg=-Tdefmt.x"]

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "debug"
