name = "rcade.dev"
compatibility_date = "2024-11-25"
main = ".svelte-kit/cloudflare/_worker.js"
account_id = "9aee291c8fc8a03f6dacc66454177c60"
compatibility_flags = ["nodejs_compat"]

[vars]
BUCKET_S3_ENDPOINT = "https://9aee291c8fc8a03f6dacc66454177c60.r2.cloudflarestorage.com/rcade"

[build]
command = "bun x vite build"

[assets]
directory = ".svelte-kit/cloudflare/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "rcade"
database_id = "c74c6e00-e3b7-4f18-aad1-76fa8b901d6c"
migrations_dir = "drizzle/migrations"

[[r2_buckets]]
binding = "STORE"
bucket_name = "rcade"

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true
